use std::fmt;

#[derive(Debug)]
pub enum Version {
    Armv8p0a,
    Armv8p1a,
    Armv8p2a,
    Armv8p3a,
    Armv8p4a,
    Armv8p5a,
    Armv8p6a,
    Armv8p7a,
    Armv8p8a,
    Armv8p9a,
    Armv9p0a,
    Armv9p1a,
    Armv9p2a,
    Armv9p3a,
    Armv9p4a,
}

impl fmt::Display for Version {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        use Version::*;
        match self {
            Armv8p0a => write!(f, "Armv8.0-a"),
            Armv8p1a => write!(f, "Armv8.1-a"),
            Armv8p2a => write!(f, "Armv8.2-a"),
            Armv8p3a => write!(f, "Armv8.3-a"),
            Armv8p4a => write!(f, "Armv8.4-a"),
            Armv8p5a => write!(f, "Armv8.5-a"),
            Armv8p6a => write!(f, "Armv8.6-a"),
            Armv8p7a => write!(f, "Armv8.7-a"),
            Armv8p8a => write!(f, "Armv8.8-a"),
            Armv8p9a => write!(f, "Armv8.9-a"),
            Armv9p0a => write!(f, "Armv9.0-a"),
            Armv9p1a => write!(f, "Armv9.1-a"),
            Armv9p2a => write!(f, "Armv9.2-a"),
            Armv9p3a => write!(f, "Armv9.3-a"),
            Armv9p4a => write!(f, "Armv9.4-a"),
        }
    }
}

impl Version {
    fn has(&self, feat: Feature) -> bool {
        use Version::*;
        match self {
            Armv8p0a => panic!("Feature list not supported yet for {self}"),
            Armv8p1a => panic!("Feature list not supported yet for {self}"),
            Armv8p2a => panic!("Feature list not supported yet for {self}"),
            Armv8p3a => panic!("Feature list not supported yet for {self}"),
            Armv8p4a => panic!("Feature list not supported yet for {self}"),
            Armv8p5a => panic!("Feature list not supported yet for {self}"),
            Armv8p6a => panic!("Feature list not supported yet for {self}"),
            Armv8p7a => panic!("Feature list not supported yet for {self}"),
            Armv8p8a => panic!("Feature list not supported yet for {self}"),
            Armv8p9a => panic!("Feature list not supported yet for {self}"),
            Armv9p0a => panic!("Feature list not supported yet for {self}"),
            Armv9p1a => panic!("Feature list not supported yet for {self}"),
            Armv9p2a => panic!("Feature list not supported yet for {self}"),
            Armv9p3a => panic!("Feature list not supported yet for {self}"),
            Armv9p4a => v9p4a_has_feat(feat),
        }
    }
}

#[derive(Debug)]
enum Feature {
    FeatAA32EL0,
    FeatAA32EL1,
    FeatAA32EL2,
    FeatAA32EL3,
    FeatAA64EL0,
    FeatAA64EL1,
    FeatAA64EL2,
    FeatAA64EL3,
    FeatEL0,
    FeatEL1,
    FeatEL2,
    FeatEL3,
    FeatAES,
    FeatAdvSIMD,
    FeatCSV2_1p1,
    FeatCSV2_1p2,
    FeatCSV2_2,
    FeatCSV2_3,
    FeatDoubleLock,
    FeatETMv4,
    FeatETMv4p1,
    FeatETMv4p2,
    FeatETMv4p3,
    FeatETMv4p4,
    FeatETMv4p5,
    FeatETMv4p6,
    FeatETS2,
    FeatFP,
    FeatGICv3,
    FeatGicv3Legacy,
    FeatGicv3Tdir,
    FeatGICv3p1,
    FeatGICv4,
    FeatGICv4p1,
    FeatIVIPT,
    FeatPCSRv8,
    FeatPMULL,
    FeatPMUv3,
    FeatPmuv3Ext,
    FeatPmuv3Ext32,
    FeatSHA1,
    FeatSHA256,
    FeatTrcExt,
    FeatTrcSr,
    FeatnTLBPA,
    FeatCRC32,
    FeatDebugv8p1,
    FeatHAFDBS,
    FeatHPDS,
    FeatLOR,
    FeatLSE,
    FeatPAN,
    FeatPMUv3p1,
    FeatRDM,
    FeatVHE,
    FeatVMID16,
    FeatAA32BF16,
    FeatAA32HPD,
    FeatAA32I8MM,
    FeatASMv8p2,
    FeatDPB,
    FeatDebugv8p2,
    FeatEDHSR,
    FeatF32MM,
    FeatF64MM,
    FeatFP16,
    FeatHPDS2,
    FeatI8MM,
    FeatIESB,
    FeatLPA,
    FeatLSMAOC,
    FeatLVA,
    FeatMPAM,
    FeatPAN2,
    FeatPCSRv8p2,
    FeatRAS,
    FeatSHA3,
    FeatSHA512,
    FeatSM3,
    FeatSM4,
    FeatSPE,
    FeatSVE,
    FeatTTCNP,
    FeatUAO,
    FeatVPIPT,
    FeatXNX,
    FeatCCIDX,
    FeatCONSTPACFIELD,
    FeatEPAC,
    FeatFCMA,
    FeatFPAC,
    FeatFPACCOMBINE,
    FeatJSCVT,
    FeatLRCPC,
    FeatNV,
    FeatPACIMP,
    FeatPACQARMA3,
    FeatPACQARMA5,
    FeatPAuth,
    FeatSPEv1p1,
    FeatAMUv1,
    FeatBBM,
    FeatCNTSC,
    FeatDIT,
    FeatDebugv8p4,
    FeatDotProd,
    FeatDoubleFault,
    FeatFHM,
    FeatFlagM,
    FeatIDST,
    FeatLRCPC2,
    FeatLSE2,
    FeatNV2,
    FeatPMUv3p4,
    FeatRASSAv1p1,
    FeatRASv1p1,
    FeatS2FWB,
    FeatSEL2,
    FeatTLBIOS,
    FeatTLBIRANGE,
    FeatTRF,
    FeatTTL,
    FeatTTST,
    FeatBTI,
    FeatCSV2,
    FeatCSV3,
    FeatDPB2,
    FeatE0PD,
    FeatEVT,
    FeatExS,
    FeatFRINTTS,
    FeatFlagM2,
    FeatGTG,
    FeatMTE,
    FeatMTE2,
    FeatPMUv3p5,
    FeatRNG,
    FeatRngTrap,
    FeatSB,
    FeatSPECRES,
    FeatSSBS,
    FeatSSBS2,
    FeatAMUv1p1,
    FeatBF16,
    FeatDGH,
    FeatECV,
    FeatFGT,
    FeatHPMN0,
    FeatMPAMv0p1,
    FeatMPAMv1p1,
    FeatMTPMU,
    FeatPAuth2,
    FeatTWED,
    FeatAFP,
    FeatEBF16,
    FeatHCX,
    FeatLPA2,
    FeatLS64,
    FeatLs64Accdata,
    FeatLs64V,
    FeatMTE3,
    FeatPAN3,
    FeatPMUv3p7,
    FeatRPRES,
    FeatSPEv1p2,
    FeatWFxT,
    FeatXS,
    FeatCMOW,
    FeatDebugv8p8,
    FeatGicv3Nmi,
    FeatHBC,
    FeatMOPS,
    FeatNMI,
    FeatPmuv3Ext64,
    FeatPmuv3Th,
    FeatPMUv3p8,
    FeatSCTLR2,
    FeatSPEv1p3,
    FeatTCR2,
    FeatTIDCP1,
    FeatADERR,
    FeatAIE,
    FeatANERR,
    FeatCLRBHB,
    FeatCSSC,
    FeatDebugv8p9,
    FeatDoubleFault2,
    FeatECBHB,
    FeatFGT2,
    FeatHAFT,
    FeatLRCPC3,
    FeatMTE4,
    FeatMteAsymFault,
    FeatMteAsync,
    FeatMteCanonicalTags,
    FeatMteNoAddressTags,
    FeatMtePerm,
    FeatMteStoreOnly,
    FeatMteTaggedFar,
    FeatPCSRv8p9,
    FeatPFAR,
    FeatPmuv3Edge,
    FeatPmuv3Icntr,
    FeatPmuv3Ss,
    FeatPMUv3p9,
    FeatPRFMSLC,
    FeatRASSAv2,
    FeatRASv2,
    FeatRPRFM,
    FeatS1PIE,
    FeatS1POE,
    FeatS2PIE,
    FeatS2POE,
    FeatSPECRES2,
    FeatSpeCrr,
    FeatSpeFds,
    FeatSPEv1p4,
    FeatSPMU,
    FeatTHE,
    FeatDoPD,
    FeatETE,
    FeatSVE2,
    FeatSveAes,
    FeatSveBitPerm,
    FeatSvePmull128,
    FeatSveSha3,
    FeatSveSm4,
    FeatTME,
    FeatTRBE,
    FeatETEv1p1,
    FeatBRBE,
    FeatETEv1p2,
    FeatRME,
    FeatSME,
    FeatSmeF64f64,
    FeatSmeFa64,
    FeatSmeI16i64,
    FeatBRBEv1p1,
    FeatMEC,
    FeatSME2,
    FeatABLE,
    FeatCHK,
    FeatD128,
    FeatEBEP,
    FeatETEv1p3,
    FeatGCS,
    FeatITE,
    FeatLSE128,
    FeatLVA3,
    FeatSEBEP,
    FeatSME2p1,
    FeatSmeF16f16,
    FeatSVE2p1,
    FeatSveB16b16,
    FeatSYSINSTR128,
    FeatSYSREG128,
    FeatTrbeExt,
    FeatTrbeMpam,
}

fn v9p4a_has_feat(feat: Feature) -> bool {
    use Feature::*;
    match feat {
        FeatAA32EL0 => true,
        FeatAA32EL1 => false,
        FeatAA32EL2 => false,
        FeatAA32EL3 => false,
        FeatAA64EL0 => true,
        FeatAA64EL1 => true,
        FeatAA64EL2 => true,
        FeatAA64EL3 => true,
        FeatEL0 => true,
        FeatEL1 => true,
        FeatEL2 => true,
        FeatEL3 => true,
        FeatAES => true,
        FeatAdvSIMD => true,
        FeatCSV2_1p1 => true,
        FeatCSV2_1p2 => true,
        FeatCSV2_2 => true,
        FeatCSV2_3 => true,
        FeatDoubleLock => true,
        FeatETMv4 => false,
        FeatETMv4p1 => true,
        FeatETMv4p2 => true,
        FeatETMv4p3 => true,
        FeatETMv4p4 => true,
        FeatETMv4p5 => true,
        FeatETMv4p6 => true,
        FeatETS2 => true,
        FeatFP => true,
        FeatGICv3 => true,
        FeatGicv3Legacy => true,
        FeatGicv3Tdir => true,
        FeatGICv3p1 => true,
        FeatGICv4 => true,
        FeatGICv4p1 => true,
        FeatIVIPT => true,
        FeatPCSRv8 => true,
        FeatPMULL => true,
        FeatPMUv3 => true,
        FeatPmuv3Ext => true,
        FeatPmuv3Ext32 => true,
        FeatSHA1 => true,
        FeatSHA256 => true,
        FeatTrcExt => true,
        FeatTrcSr => true,
        FeatnTLBPA => true,
        FeatCRC32 => true,
        FeatDebugv8p1 => true,
        FeatHAFDBS => true,
        FeatHPDS => true,
        FeatLOR => true,
        FeatLSE => true,
        FeatPAN => true,
        FeatPMUv3p1 => true,
        FeatRDM => true,
        FeatVHE => true,
        FeatVMID16 => true,
        FeatAA32BF16 => true,
        FeatAA32HPD => true,
        FeatAA32I8MM => true,
        FeatASMv8p2 => true,
        FeatDPB => true,
        FeatDebugv8p2 => true,
        FeatEDHSR => true,
        FeatF32MM => true,
        FeatF64MM => true,
        FeatFP16 => true,
        FeatHPDS2 => true,
        FeatI8MM => true,
        FeatIESB => true,
        FeatLPA => true,
        FeatLSMAOC => true,
        FeatLVA => true,
        FeatMPAM => true,
        FeatPAN2 => true,
        FeatPCSRv8p2 => true,
        FeatRAS => true,
        FeatSHA3 => true,
        FeatSHA512 => true,
        FeatSM3 => true,
        FeatSM4 => true,
        FeatSPE => true,
        FeatSVE => true,
        FeatTTCNP => true,
        FeatUAO => true,
        FeatVPIPT => true,
        FeatXNX => true,
        FeatCCIDX => true,
        FeatCONSTPACFIELD => false,
        FeatEPAC => false,
        FeatFCMA => true,
        FeatFPAC => true,
        FeatFPACCOMBINE => true,
        FeatJSCVT => true,
        FeatLRCPC => true,
        FeatNV => true,
        FeatPACIMP => false,
        FeatPACQARMA3 => false,
        FeatPACQARMA5 => true,
        FeatPAuth => true,
        FeatSPEv1p1 => true,
        FeatAMUv1 => true,
        FeatBBM => true,
        FeatCNTSC => true,
        FeatDIT => true,
        FeatDebugv8p4 => true,
        FeatDotProd => true,
        FeatDoubleFault => true,
        FeatFHM => true,
        FeatFlagM => true,
        FeatIDST => true,
        FeatLRCPC2 => true,
        FeatLSE2 => true,
        FeatNV2 => true,
        FeatPMUv3p4 => true,
        FeatRASSAv1p1 => true,
        FeatRASv1p1 => true,
        FeatS2FWB => true,
        FeatSEL2 => true,
        FeatTLBIOS => true,
        FeatTLBIRANGE => true,
        FeatTRF => true,
        FeatTTL => true,
        FeatTTST => true,
        FeatBTI => true,
        FeatCSV2 => true,
        FeatCSV3 => true,
        FeatDPB2 => true,
        FeatE0PD => true,
        FeatEVT => true,
        FeatExS => true,
        FeatFRINTTS => true,
        FeatFlagM2 => true,
        FeatGTG => true,
        FeatMTE => true,
        FeatMTE2 => true,
        FeatPMUv3p5 => true,
        FeatRNG => true,
        FeatRngTrap => true,
        FeatSB => true,
        FeatSPECRES => true,
        FeatSSBS => true,
        FeatSSBS2 => true,
        FeatAMUv1p1 => true,
        FeatBF16 => true,
        FeatDGH => true,
        FeatECV => true,
        FeatFGT => true,
        FeatHPMN0 => true,
        FeatMPAMv0p1 => true,
        FeatMPAMv1p1 => true,
        FeatMTPMU => true,
        FeatPAuth2 => true,
        FeatTWED => true,
        FeatAFP => true,
        FeatEBF16 => true,
        FeatHCX => true,
        FeatLPA2 => true,
        FeatLS64 => true,
        FeatLs64Accdata => true,
        FeatLs64V => true,
        FeatMTE3 => true,
        FeatPAN3 => true,
        FeatPMUv3p7 => true,
        FeatRPRES => true,
        FeatSPEv1p2 => true,
        FeatWFxT => true,
        FeatXS => true,
        FeatCMOW => true,
        FeatDebugv8p8 => true,
        FeatGicv3Nmi => true,
        FeatHBC => true,
        FeatMOPS => true,
        FeatNMI => true,
        FeatPmuv3Ext64 => true,
        FeatPmuv3Th => true,
        FeatPMUv3p8 => true,
        FeatSCTLR2 => true,
        FeatSPEv1p3 => true,
        FeatTCR2 => true,
        FeatTIDCP1 => true,
        FeatADERR => true,
        FeatAIE => true,
        FeatANERR => true,
        FeatCLRBHB => true,
        FeatCSSC => true,
        FeatDebugv8p9 => true,
        FeatDoubleFault2 => true,
        FeatECBHB => true,
        FeatFGT2 => true,
        FeatHAFT => true,
        FeatLRCPC3 => true,
        FeatMTE4 => true,
        FeatMteAsymFault => true,
        FeatMteAsync => true,
        FeatMteCanonicalTags => true,
        FeatMteNoAddressTags => true,
        FeatMtePerm => true,
        FeatMteStoreOnly => true,
        FeatMteTaggedFar => true,
        FeatPCSRv8p9 => true,
        FeatPFAR => true,
        FeatPmuv3Edge => true,
        FeatPmuv3Icntr => true,
        FeatPmuv3Ss => true,
        FeatPMUv3p9 => true,
        FeatPRFMSLC => true,
        FeatRASSAv2 => true,
        FeatRASv2 => true,
        FeatRPRFM => true,
        FeatS1PIE => true,
        FeatS1POE => true,
        FeatS2PIE => true,
        FeatS2POE => true,
        FeatSPECRES2 => true,
        FeatSpeCrr => true,
        FeatSpeFds => true,
        FeatSPEv1p4 => true,
        FeatSPMU => true,
        FeatTHE => true,
        FeatDoPD => true,
        FeatETE => true,
        FeatSVE2 => true,
        FeatSveAes => true,
        FeatSveBitPerm => true,
        FeatSvePmull128 => true,
        FeatSveSha3 => true,
        FeatSveSm4 => true,
        FeatTME => true,
        FeatTRBE => true,
        FeatETEv1p1 => true,
        FeatBRBE => true,
        FeatETEv1p2 => true,
        FeatRME => true,
        FeatSME => true,
        FeatSmeF64f64 => true,
        FeatSmeFa64 => true,
        FeatSmeI16i64 => true,
        FeatBRBEv1p1 => true,
        FeatMEC => true,
        FeatSME2 => true,
        FeatABLE => true,
        FeatCHK => true,
        FeatD128 => true,
        FeatEBEP => true,
        FeatETEv1p3 => true,
        FeatGCS => true,
        FeatITE => true,
        FeatLSE128 => true,
        FeatLVA3 => true,
        FeatSEBEP => true,
        FeatSME2p1 => true,
        FeatSmeF16f16 => true,
        FeatSVE2p1 => true,
        FeatSveB16b16 => true,
        FeatSYSINSTR128 => true,
        FeatSYSREG128 => true,
        FeatTrbeExt => true,
        FeatTrbeMpam => true,
    }
}
