#[derive(Clone, Copy)]
pub enum Feat {
    AA32EL0,
    AA32EL1,
    AA32EL2,
    AA32EL3,
    AA64EL0,
    AA64EL1,
    AA64EL2,
    AA64EL3,
    EL0,
    EL1,
    EL2,
    EL3,
    AES,
    AdvSIMD,
    ASID2,
    CSV2_1p1,
    CSV2_1p2,
    CSV2_2,
    CSV2_3,
    DoubleLock,
    ETMv4,
    ETMv4p1,
    ETMv4p2,
    ETMv4p3,
    ETMv4p4,
    ETMv4p5,
    ETMv4p6,
    ETS2,
    FP,
    GICv3,
    Gicv3Legacy,
    Gicv3Tdir,
    GICv3p1,
    GICv4,
    GICv4p1,
    IVIPT,
    PCSRv8,
    PMULL,
    PMUv3,
    Pmuv3Ext,
    Pmuv3Ext32,
    SHA1,
    SHA256,
    TrcExt,
    TrcSr,
    NTLBPA,
    CRC32,
    Debugv8p1,
    HAFDBS,
    HPDS,
    LOR,
    LSE,
    PAN,
    PMUv3p1,
    RDM,
    VHE,
    VMID16,
    AA32BF16,
    AA32HPD,
    AA32I8MM,
    ASMv8p2,
    DPB,
    Debugv8p2,
    EDHSR,
    F32MM,
    F64MM,
    FP16,
    HPDS2,
    I8MM,
    IESB,
    LPA,
    LSMAOC,
    LVA,
    MPAM,
    PAN2,
    PCSRv8p2,
    RAS,
    SHA3,
    SHA512,
    SM3,
    SM4,
    SPE,
    SVE,
    TTCNP,
    UAO,
    VPIPT,
    XNX,
    CCIDX,
    CONSTPACFIELD,
    EPAC,
    FCMA,
    FPAC,
    FPACCOMBINE,
    JSCVT,
    LRCPC,
    NV,
    PACIMP,
    PACQARMA3,
    PACQARMA5,
    PAuth,
    SPEv1p1,
    AMUv1,
    BBM,
    CNTSC,
    DIT,
    Debugv8p4,
    DotProd,
    DoubleFault,
    FHM,
    FlagM,
    IDST,
    LRCPC2,
    LSE2,
    NV2,
    PMUv3p4,
    RASSAv1p1,
    RASv1p1,
    S2FWB,
    SEL2,
    TLBIOS,
    TLBIRANGE,
    TRF,
    TTL,
    TTST,
    BTI,
    CSV2,
    CSV3,
    DPB2,
    E0PD,
    EVT,
    ExS,
    FRINTTS,
    FlagM2,
    GTG,
    MTE,
    MTE2,
    PMUv3p5,
    RNG,
    RngTrap,
    SB,
    SPECRES,
    SSBS,
    SSBS2,
    AMUv1p1,
    BF16,
    DGH,
    ECV,
    FGT,
    HPMN0,
    MPAMv0p1,
    MPAMv1p1,
    MTPMU,
    PAuth2,
    TWED,
    AFP,
    EBF16,
    HCX,
    LPA2,
    LS64,
    Ls64Accdata,
    Ls64V,
    MTE3,
    PAN3,
    PMUv3p7,
    RPRES,
    SPEv1p2,
    WFxT,
    XS,
    CMOW,
    Debugv8p8,
    Gicv3Nmi,
    HBC,
    MOPS,
    NMI,
    Pmuv3Ext64,
    Pmuv3Th,
    PMUv3p8,
    SCTLR2,
    SPEv1p3,
    TCR2,
    TIDCP1,
    ADERR,
    AIE,
    ANERR,
    CLRBHB,
    CSSC,
    Debugv8p9,
    DoubleFault2,
    ECBHB,
    FGT2,
    HAFT,
    LRCPC3,
    MTE4,
    MteAsymFault,
    MteAsync,
    MteCanonicalTags,
    MteNoAddressTags,
    MtePerm,
    MteStoreOnly,
    MteTaggedFar,
    PCSRv8p9,
    PFAR,
    Pmuv3Edge,
    Pmuv3Icntr,
    Pmuv3Ss,
    PMUv3p9,
    PRFMSLC,
    RASSAv2,
    RASv2,
    RPRFM,
    S1PIE,
    S1POE,
    S2PIE,
    S2POE,
    SPECRES2,
    SpeCrr,
    SpeFds,
    SPEv1p4,
    SPMU,
    THE,
    DoPD,
    ETE,
    SVE2,
    SveAes,
    SveBitPerm,
    SvePmull128,
    SveSha3,
    SveSm4,
    TME,
    TRBE,
    ETEv1p1,
    BRBE,
    ETEv1p2,
    RME,
    SME,
    SmeF64f64,
    SmeFa64,
    SmeI16i64,
    BRBEv1p1,
    MEC,
    SME2,
    ABLE,
    CHK,
    D128,
    EBEP,
    ETEv1p3,
    GCS,
    ITE,
    LSE128,
    LVA3,
    SEBEP,
    SME2p1,
    SmeF16f16,
    SVE2p1,
    SveB16b16,
    SYSINSTR128,
    SYSREG128,
    TrbeExt,
    TrbeMpam,
    E2H0,
    PAuthLR,
    HDBSS,
    CPA,
    CPA2,
}

pub fn v9p4a_is_feat_impl(feat: Feat) -> bool {
    use Feat::*;
    match feat {
        AA32EL0 => true,
        AA32EL1 => false,
        AA32EL2 => false,
        AA32EL3 => false,
        AA64EL0 => true,
        AA64EL1 => true,
        AA64EL2 => true,
        AA64EL3 => true,
        EL0 => true,
        EL1 => true,
        EL2 => true,
        EL3 => true,
        AES => true,
        AdvSIMD => true,
        ASID2 => false,
        CSV2_1p1 => true,
        CSV2_1p2 => true,
        CSV2_2 => true,
        CSV2_3 => true,
        DoubleLock => true,
        ETMv4 => false,
        ETMv4p1 => true,
        ETMv4p2 => true,
        ETMv4p3 => true,
        ETMv4p4 => true,
        ETMv4p5 => true,
        ETMv4p6 => true,
        ETS2 => true,
        FP => true,
        GICv3 => true,
        Gicv3Legacy => true,
        Gicv3Tdir => true,
        GICv3p1 => true,
        GICv4 => true,
        GICv4p1 => true,
        IVIPT => true,
        PCSRv8 => true,
        PMULL => true,
        PMUv3 => true,
        Pmuv3Ext => true,
        Pmuv3Ext32 => true,
        SHA1 => true,
        SHA256 => true,
        TrcExt => true,
        TrcSr => true,
        NTLBPA => true,
        CRC32 => true,
        Debugv8p1 => true,
        HAFDBS => true,
        HPDS => true,
        LOR => true,
        LSE => true,
        PAN => true,
        PMUv3p1 => true,
        RDM => true,
        VHE => true,
        VMID16 => true,
        AA32BF16 => true,
        AA32HPD => true,
        AA32I8MM => true,
        ASMv8p2 => true,
        DPB => true,
        Debugv8p2 => true,
        EDHSR => true,
        F32MM => true,
        F64MM => true,
        FP16 => true,
        HPDS2 => true,
        I8MM => true,
        IESB => true,
        LPA => true,
        LSMAOC => true,
        LVA => true,
        MPAM => true,
        PAN2 => true,
        PCSRv8p2 => true,
        RAS => true,
        SHA3 => true,
        SHA512 => true,
        SM3 => true,
        SM4 => true,
        SPE => true,
        SVE => true,
        TTCNP => true,
        UAO => true,
        VPIPT => true,
        XNX => true,
        CCIDX => true,
        CONSTPACFIELD => false,
        EPAC => false,
        FCMA => true,
        FPAC => true,
        FPACCOMBINE => true,
        JSCVT => true,
        LRCPC => true,
        NV => true,
        PACIMP => false,
        PACQARMA3 => false,
        PACQARMA5 => true,
        PAuth => true,
        SPEv1p1 => true,
        AMUv1 => true,
        BBM => true,
        CNTSC => true,
        DIT => true,
        Debugv8p4 => true,
        DotProd => true,
        DoubleFault => true,
        FHM => true,
        FlagM => true,
        IDST => true,
        LRCPC2 => true,
        LSE2 => true,
        NV2 => true,
        PMUv3p4 => true,
        RASSAv1p1 => true,
        RASv1p1 => true,
        S2FWB => true,
        SEL2 => true,
        TLBIOS => true,
        TLBIRANGE => true,
        TRF => true,
        TTL => true,
        TTST => true,
        BTI => true,
        CSV2 => true,
        CSV3 => true,
        DPB2 => true,
        E0PD => true,
        EVT => true,
        ExS => true,
        FRINTTS => true,
        FlagM2 => true,
        GTG => true,
        MTE => true,
        MTE2 => true,
        PMUv3p5 => true,
        RNG => true,
        RngTrap => true,
        SB => true,
        SPECRES => true,
        SSBS => true,
        SSBS2 => true,
        AMUv1p1 => true,
        BF16 => true,
        DGH => true,
        ECV => true,
        FGT => true,
        HPMN0 => true,
        MPAMv0p1 => true,
        MPAMv1p1 => true,
        MTPMU => true,
        PAuth2 => true,
        TWED => true,
        AFP => true,
        EBF16 => true,
        HCX => true,
        LPA2 => true,
        LS64 => true,
        Ls64Accdata => true,
        Ls64V => true,
        MTE3 => true,
        PAN3 => true,
        PMUv3p7 => true,
        RPRES => true,
        SPEv1p2 => true,
        WFxT => true,
        XS => true,
        CMOW => true,
        Debugv8p8 => true,
        Gicv3Nmi => true,
        HBC => true,
        MOPS => true,
        NMI => true,
        Pmuv3Ext64 => true,
        Pmuv3Th => true,
        PMUv3p8 => true,
        SCTLR2 => true,
        SPEv1p3 => true,
        TCR2 => true,
        TIDCP1 => true,
        ADERR => true,
        AIE => true,
        ANERR => true,
        CLRBHB => true,
        CSSC => true,
        Debugv8p9 => true,
        DoubleFault2 => true,
        ECBHB => true,
        FGT2 => true,
        HAFT => true,
        LRCPC3 => true,
        MTE4 => true,
        MteAsymFault => true,
        MteAsync => true,
        MteCanonicalTags => true,
        MteNoAddressTags => true,
        MtePerm => true,
        MteStoreOnly => true,
        MteTaggedFar => true,
        PCSRv8p9 => true,
        PFAR => true,
        Pmuv3Edge => true,
        Pmuv3Icntr => true,
        Pmuv3Ss => true,
        PMUv3p9 => true,
        PRFMSLC => true,
        RASSAv2 => true,
        RASv2 => true,
        RPRFM => true,
        S1PIE => true,
        S1POE => true,
        S2PIE => true,
        S2POE => true,
        SPECRES2 => true,
        SpeCrr => true,
        SpeFds => true,
        SPEv1p4 => true,
        SPMU => true,
        THE => true,
        DoPD => true,
        ETE => true,
        SVE2 => true,
        SveAes => true,
        SveBitPerm => true,
        SvePmull128 => true,
        SveSha3 => true,
        SveSm4 => true,
        TME => true,
        TRBE => true,
        ETEv1p1 => true,
        BRBE => true,
        ETEv1p2 => true,
        RME => true,
        SME => true,
        SmeF64f64 => true,
        SmeFa64 => true,
        SmeI16i64 => true,
        BRBEv1p1 => true,
        MEC => true,
        SME2 => true,
        ABLE => true,
        CHK => true,
        D128 => true,
        EBEP => true,
        ETEv1p3 => true,
        GCS => true,
        ITE => true,
        LSE128 => true,
        LVA3 => true,
        SEBEP => true,
        SME2p1 => true,
        SmeF16f16 => true,
        SVE2p1 => true,
        SveB16b16 => true,
        SYSINSTR128 => true,
        SYSREG128 => true,
        TrbeExt => true,
        TrbeMpam => true,
        E2H0 => true,
        PAuthLR => true,
        HDBSS => true,
        CPA => true,
        CPA2 => true,
    }
}
